/**
 * HTML Minification Script
 * Minifies all HTML files in _site directory
 */

import { minify } from 'html-minifier-terser';
import { promises as fs } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SITE_DIR = path.join(__dirname, '..', '_site');

const minifyOptions = {
  collapseBooleanAttributes: true,
  collapseWhitespace: true,
  conservativeCollapse: true,
  decodeEntities: true,
  html5: true,
  includeAutoGeneratedTags: false,
  keepClosingSlash: true,
  minifyCSS: true,
  minifyJS: true,
  minifyURLs: true,
  preserveLineBreaks: false,
  preventAttributesEscaping: false,
  processConditionalComments: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: true,
  removeOptionalTags: false,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  sortAttributes: true,
  sortClassName: true,
  useShortDoctype: true,
};

async function findHTMLFiles(dir) {
  const files = await fs.readdir(dir, { withFileTypes: true });
  const htmlFiles = [];

  for (const file of files) {
    const fullPath = path.join(dir, file.name);

    if (file.isDirectory()) {
      htmlFiles.push(...(await findHTMLFiles(fullPath)));
    } else if (file.name.endsWith('.html')) {
      htmlFiles.push(fullPath);
    }
  }

  return htmlFiles;
}

async function minifyHTMLFile(filePath) {
  try {
    const html = await fs.readFile(filePath, 'utf8');
    const originalSize = Buffer.byteLength(html, 'utf8');

    const minified = await minify(html, minifyOptions);
    const minifiedSize = Buffer.byteLength(minified, 'utf8');

    await fs.writeFile(filePath, minified, 'utf8');

    const savings = originalSize - minifiedSize;
    const percent = ((savings / originalSize) * 100).toFixed(1);

    return { originalSize, minifiedSize, savings, percent };
  } catch (error) {
    console.error(`Error minifying ${filePath}:`, error.message);
    return null;
  }
}

async function main() {
  console.log('🗜️  Starting HTML minification...\n');

  try {
    const htmlFiles = await findHTMLFiles(SITE_DIR);
    console.log(`Found ${htmlFiles.length} HTML files\n`);

    let totalOriginal = 0;
    let totalMinified = 0;
    let processedCount = 0;

    for (const file of htmlFiles) {
      const result = await minifyHTMLFile(file);

      if (result) {
        const relativePath = path.relative(SITE_DIR, file);
        console.log(
          `✓ ${relativePath}: ${result.originalSize} → ${result.minifiedSize} bytes (${result.percent}% savings)`
        );

        totalOriginal += result.originalSize;
        totalMinified += result.minifiedSize;
        processedCount++;
      }
    }

    const totalSavings = totalOriginal - totalMinified;
    const totalPercent = ((totalSavings / totalOriginal) * 100).toFixed(1);

    console.log('\n📊 Summary:');
    console.log(`   Files processed: ${processedCount}`);
    console.log(`   Original size: ${(totalOriginal / 1024).toFixed(2)} KB`);
    console.log(`   Minified size: ${(totalMinified / 1024).toFixed(2)} KB`);
    console.log(`   Total savings: ${(totalSavings / 1024).toFixed(2)} KB (${totalPercent}%)`);
    console.log('\n✨ HTML minification complete!');
  } catch (error) {
    console.error('❌ Error during minification:', error);
    process.exit(1);
  }
}

main();
